// <auto-generated />
namespace Microservice.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateTableSkillStudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTableSkillStudent));
        
        string IMigrationMetadata.Id
        {
            get { return "201901290943200_updateTableSkillStudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
